package:
  name: occ_airconics
  version: {{  environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../../

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - pythonocc-core
    - numpy
    - six

test:
  imports:
    - airconics

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}


about:
  home: https://github.com/p-chambers/occ_airconics/
  summary: "Scripted Aircraft Geometry Module based on Python-OCC"
