package:
  name: occ_airconics
  version: '{{ environ.get("OCC_AIRCONICS_VERSION") }}'

source:
  git_url: https://github.com/p-chambers/occ_airconics
  git_tag: release0.2

requirements:
  build:
    - python
    - setuptools
    - pythonocc-core
    - numpy
    - setuptools_scm
  run:
    - python
    - pythonocc-core
    - numpy

test:
  imports:
    - airconics

about:
  home: https://github.com/p-chambers/occ_airconics/
  summary: "Scripted Aircraft Geometry Module based on Python-OCC"
